### ISSUE TITLE
upgrade to graphframes 0.6

### ISSUE THREAD

**Issue by zhiboz** [rstudio/graphframes#9]
graphframes 0.6 was released few days back, which comes with support to spark 2.2+. it may make sense to update the dependency to graphframes v0.6 in place of v0.5.

**Comment by harryprince** [comment]
running spark2.2.1 and graphframe 0.1.1 fail:

```
		::::::::::::::::::::::::::::::::::::::::::::::

		::          UNRESOLVED DEPENDENCIES         ::

		::::::::::::::::::::::::::::::::::::::::::::::

		:: graphframes#graphframes;0.5.0-spark2.2-s_2.11: not found

		::::::::::::::::::::::::::::::::::::::::::::::
```

only `0.6.0-spark2.2-s_2.11`
can be found in here https://dl.bintray.com/spark-packages/maven/graphframes/graphframes/
